python get_activated_images.py -a alex --finetune -b 10 -l conv1 -n ./alex/acts_conv1.npy -v ./ilsvrc_val.txt -r /home/isl-ws16/Caffe/data/ilsvrc12/resize/val -o .
python get_activated_images.py -a alex --finetune -b 10 -l conv2 -n ./alex/acts_conv2.npy -v ./ilsvrc_val.txt -r /home/isl-ws16/Caffe/data/ilsvrc12/resize/val -o .
python get_activated_images.py -a alex --finetune -b 10 -l conv3 -n ./alex/acts_conv3.npy -v ./ilsvrc_val.txt -r /home/isl-ws16/Caffe/data/ilsvrc12/resize/val -o .
python get_activated_images.py -a alex --finetune -b 10 -l conv4 -n ./alex/acts_conv4.npy -v ./ilsvrc_val.txt -r /home/isl-ws16/Caffe/data/ilsvrc12/resize/val -o .
python get_activated_images.py -a alex --finetune -b 10 -l conv5 -n ./alex/acts_conv5.npy -v ./ilsvrc_val.txt -r /home/isl-ws16/Caffe/data/ilsvrc12/resize/val -o .
python get_activated_images.py -a alex --finetune -b 10 -l pool1 -n ./alex/acts_pool1.npy -v ./ilsvrc_val.txt -r /home/isl-ws16/Caffe/data/ilsvrc12/resize/val -o .
python get_activated_images.py -a alex --finetune -b 10 -l pool2 -n ./alex/acts_pool2.npy -v ./ilsvrc_val.txt -r /home/isl-ws16/Caffe/data/ilsvrc12/resize/val -o .
python get_activated_images.py -a alex --finetune -b 10 -l pool5 -n ./alex/acts_pool5.npy -v ./ilsvrc_val.txt -r /home/isl-ws16/Caffe/data/ilsvrc12/resize/val -o .
python get_activated_images.py -a alex --finetune -b 10 -l relu1 -n ./alex/acts_relu1.npy -v ./ilsvrc_val.txt -r /home/isl-ws16/Caffe/data/ilsvrc12/resize/val -o .
python get_activated_images.py -a alex --finetune -b 10 -l relu2 -n ./alex/acts_relu2.npy -v ./ilsvrc_val.txt -r /home/isl-ws16/Caffe/data/ilsvrc12/resize/val -o .
python get_activated_images.py -a alex --finetune -b 10 -l relu3 -n ./alex/acts_relu3.npy -v ./ilsvrc_val.txt -r /home/isl-ws16/Caffe/data/ilsvrc12/resize/val -o .
python get_activated_images.py -a alex --finetune -b 10 -l relu4 -n ./alex/acts_relu4.npy -v ./ilsvrc_val.txt -r /home/isl-ws16/Caffe/data/ilsvrc12/resize/val -o .
python get_activated_images.py -a alex --finetune -b 10 -l relu5 -n ./alex/acts_relu5.npy -v ./ilsvrc_val.txt -r /home/isl-ws16/Caffe/data/ilsvrc12/resize/val -o .
